[httpServer]
    Host = "127.0.0.1"
    Port = 8080

[grpcServer]
    Host = "127.0.0.1"
    Port = 8081

[log]
    development = true
    filePath = "/tmp/a.log"

[mysql]
    [mysql.db]
        dsn = "root:123456@tcp(127.0.0.1:3306)/hiolabsDB?charset=utf8&parseTime=True&loc=Local&readTimeout=3s&writeTimeout=3s"
         log = true
[redis]
    [redis.cache]
        dsn = "127.0.0.1:6379"
