[httpServer]
    host = "127.0.0.1"
    port = 8080
    consulAddr = "127.0.0.1:8500"

[grpcServer]
    host = "127.0.0.1"
    port = 8081
    consulAddr = "127.0.0.1:8500"

[log]
    development = true
    filePath = "./a.log"

[mysql]
    [mysql.db]
        dsn = "root:123456@tcp(127.0.0.1:3306)/dev?charset=utf8&parseTime=True&loc=Local&readTimeout=3s&writeTimeout=3s"
        log = true

[psql]
    [psql.test]
        dsn = "host=127.0.0.1 port=5432 sslmode=disable user=postgres password=123456 dbname=test"
        log = true

[redis]
    [redis.cache]
        dsn = "127.0.0.1:6379"

[server]
    name = "xiaos"